### ISSUE TITLE
Suggestion to Call Help Manually

### ISSUE THREAD

**Issue by coderangerdan** [AlexGhiondea/CommandLine#11]
First off, great project, thanks. A suggestion though, if you don't mind me asking.

When i have my command line parsed, i will get a filepath; i then need to check this filepath exists and the config file at that location parses okay, if not then i want to be able to display an error and the Detailed Help already formatted as per an error generated from the parser.

Can you add this facility so that help can be called externally?

**Comment by AlexGhiondea** [comment]
So basically you want the ability to display the help via code?

**Comment by AlexGhiondea** [comment]
The 1.4.0 package is now available with this API:

```csharp
void Parser.DisplayHelp<TOptions>(HelpFormat format = HelpFormat.Short);
```
