### ISSUE TITLE
Invalid optional argument format syntax results in bad exception msg

### ISSUE THREAD

**Issue by lucyainsworth** [AlexGhiondea/CommandLine#36]
Example:
<action_group_arg> <required_1> <required_2> <required_3> <optional_w_bad_syntax>

If someone were to supply a malformed optional argument such as "-option=value" then it will report that the previous argument was not found.  In this case that is a required argument, so the error message is misleading & incorrect.  This is caused by line 297 in Parser.cs, because it indexes into args with currentLogicalPosition without adding offsetInArray.

Using the above example syntax we can expand on the problem here:
Foo bar_req1 bar_req2 bar_re3 -optional=value

Would result in the following exception msg: "Could not find argument bar_req3"

**Comment by AlexGhiondea** [comment]
That is a great analysis of this issue! I agree with your assessment. As a fix, you can either add `offsetInArray` to the `currentLogicalPosition` when throwing the exception, or use the `optionalParamName` that is retrieved above.

@lucyainsworth are you interested in submitting a PR to address this?

**Comment by lucyainsworth** [comment]
Sure thing!  I submitted a pull request with the fix.

Thanks for the quick response Alex!

**Comment by AlexGhiondea** [comment]
This has been merged -- I will bump the package version and push a change out shortly.

**Comment by AlexGhiondea** [comment]
Package has been published.
