### ISSUE TITLE
Does this handle the string array from commandline?

### ISSUE THREAD

**Issue by zakwillis** [AlexGhiondea/CommandLine#9]
Hi, it appears this library doesn't handle a string array, i.e. where args[6] for example? If I join the string we still get no matches.

**Comment by AlexGhiondea** [comment]
@zakwillis do you have a repro I can try?

**Comment by zakwillis** [comment]
Hi Alex, just saw this. I believe this is a work project and can't send the code. I will take a look though but it looks like it is fine that you closed it. Thanks for responding.

**Comment by AlexGhiondea** [comment]
Hey @zakwillis  -- I closed it as I though you weren't going to reply :).

You don't have to send the code.. I was just wondering what you meant.

I added an API in the latest version that, given a string, it will parse it as command line arguments -- you can use that if the command line is not coming from the OS already parsed.

You can do this:
```csharp
Parser.TryParse("firstArg secondArg thirdArg");
```

Was that what you wanted to do?

**Comment by zakwillis** [comment]
Hi, Alex, yes, this is what I wanted to do. Many thanks for taking the time to reply and putting the effort in.

Best,

Zak

Sent from my Windows Phone
________________________________

**Comment by AlexGhiondea** [comment]
Great -- the new version of the library has that available!
